---
title: Dropout Genius
timezone: America/New_York
collections:
  authors:
    title: Authors
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: authors
  values:
    permalink: "/authors/:title/"
    layout: author
- scope:
    path: ''
    type: posts
  values:
    permalink: "/:title/"
    layout: post
    author:
description: Degree-Free Living
