---
title: Dropout Genius
timezone: America/New_York
collections:
  authors:
    title: Authors
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Degree-Free Living
